### ISSUE TITLE
[BUG] 发送应用消息的接口响应报缺少AccessToken

### ISSUE THREAD

**Issue by varequan** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#10]
在WechatWorkClientExecuteCgibinMessageExtensions里调用的接口请求响应报缺少AccessToken，需要加上
.SetQueryParam("access_token", request.AccessToken)

**Comment by fudiwei** [comment]
方便发个 PR 吗？


在 2021年9月12日 22:16，Vare ***@***.***> 写道：


在WechatWorkClientExecuteCgibinMessageExtensions里调用的接口请求响应报缺少AccessToken，需要加上
 .SetQueryParam("access_token", request.AccessToken)
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fudiwei** [comment]
Fix this on [release v1.3.4](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/1.3.4).
